### ISSUE TITLE
workflow composition should refer to steps, not entire nanopubs

### ISSUE THREAD

**Issue by tkuhn** [fair-workflows/FAIR-WFcollection#1]
I think in workflow composition nanopubs like [this one](https://github.com/fair-workflows/FAIR-WFcollection/blob/master/cooking_recipe/nanopub_workflow/RAcu9EPf9LamANz6FFQMsrucmFKyFfHiSq0TcbmefKVNU.trig), we should not refer to the step nanopublications like this

    <http://purl.org/np/RA...kwjhY> dul:precedes ...

But to the steps themselves like this:

    <http://purl.org/np/RA...kwjhY#step> dul:precedes ...

**Comment by raar1** [comment]
Hi Tobias, I agree. I've made some changes to the conversion, and there are a new set of example nanopubs in there now. The steps referred to by the workflow nanopub now have the #step fragment as they should.

**Comment by tkuhn** [comment]
Yes, that looks good now.
